# 使用本地电脑的MySQL数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wechat?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 137900
mybatis-plus:
  global-config:
    db-config:
      db-type: mysql
